import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar';
import Footer from '../components/footer/Footer';
import CursorBlob from '@/components/CursorBlob';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Shivansh' Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={montserrat.className}>
        <Navbar />
        <main className='body-main'>{children}</main>
        <Footer />
        <CursorBlob />
      </body>
    </html>
  );
}
